version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 1972
      - 32792:52773
      - 53773
    volumes:
      - ./:/irisdev/app

  jgw:
    image: intersystemsdc/pexoperation:latest
    build:
      context: java
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 55555:55555
    volumes:
      - ./java/src/Crypto/db:/jgw/db